# Data Cleaning

## References
* https://stackoverflow.com/questions/42063716/pandas-sum-up-multiple-columns-into-one-column-without-last-column

In [1]:
# Dependencies
import pandas as pd
import numpy as np
import datetime as dt

## Pull data from CSV files

In [2]:
# Pull in CSV as DataFrame
tops_df = pd.read_csv('tops.csv')

# View dataframe
tops_df.head()

,Unnamed: 0,Wardrobe Tracking - Start Date 12/9/2018,Wears (11/2020),Wears (10/2020),Wears (9/2020),Wears (8/2020),Wears (7/2020),Wears (6/2020),Wears (5/2020),Wears (4/2020),...,Notes,Repairs/Tailoring,CPW,Category,Subcategory - Sleeves,Color,Today,Start Date,Subcategory - Length,Type
0,0,Brian's White Buttonup LS Shirt,NaN,2.0,1.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,$0.00,shirt,long sleeve,cream/white/tan,11/11/2020,12/9/2018,NaN,Tops
1,1,Cream Turtleneck LS Shirt,NaN,1.0,1.0,NaN,NaN,STORAGE,1.0,1,...,NaN,NaN,$0.35,shirt,long sleeve,cream/white/tan,11/11/2020,12/9/2018,NaN,Tops
2,2,Tie Dye Mineo LS Shirt,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2,...,Winter Jam,NaN,$7.00,shirt,long sleeve,multi,11/11/2020,12/9/2018,NaN,Tops
3,3,Forest Green Silk LS Shirt,NaN,2.0,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,$2.30,shirt,long sleeve,green,11/11/2020,12/9/2018,NaN,Tops
4,4,Grey Heather LS Shirt,NaN,1.0,NaN,1.0,1,NaN,2.0,1,...,NaN,NaN,$0.65,shirt,long sleeve,grey,11/11/2020,12/9/2018,NaN,Tops

In [3]:
# Pull in CSV as DataFrame
outerwear_df = pd.read_csv('outerwear.csv')

# View dataframe
outerwear_df.head()

,Unnamed: 0,Wardrobe Tracking - Start Date 12/9/2018,Wears (11/2020),Wears (10/2020),Wears (9/2020),Wears (8/2020),Wears (7/2020),Wears (6/2020),Wears (5/2020),Wears (4/2020),...,Source,Notes,Repairs/Tailoring,CPW,Category,Subcategory - Sleeves,Today,Start Date,Subcategory - Length,Type
0,0,Blue Pullover Sweater,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Hand-me-down,NaN,NaN,$0.00,sweater,long sleeve,11/11/2020,12/9/2018,NaN,Outerwear
1,1,Beige Cable Knit Sweater,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,Secondhand,NaN,NaN,$2.00,sweater,long sleeve,11/11/2020,12/9/2018,NaN,Outerwear
2,2,Cream Knit Crop Sweater,1.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,$0.83,sweater,long sleeve,11/11/2020,12/9/2018,NaN,Outerwear
3,3,Purple and Orange Mockneck Sweater,1.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,Secondhand,NaN,NaN,$1.67,sweater,long sleeve,11/11/2020,12/9/2018,NaN,Outerwear
4,4,Cream Cardigan,NaN,NaN,1.0,NaN,NaN,NaN,2.0,2,...,Slow Fashion,NaN,NaN,$1.95,cardigan,long sleeve,11/11/2020,12/9/2018,NaN,Outerwear

In [4]:
# Pull in CSV
bottoms_df = pd.read_csv('bottoms.csv')

# View dataframe
bottoms_df.head()

,Unnamed: 0,Wardrobe Tracking - Start Date 12/9/2018,Wears (11/2020),Wears (10/2020),Wears (9/2020),Wears (8/2020),Wears (7/2020),Wears (6/2020),Wears (5/2020),Wears (4/2020),...,Source,Notes,Repairs/Tailoring,CPW,Category,Subcategory - Length,Today,Date Started,Subcategory - Sleeves,Type
0,0,Curator Rust CL Skirt,1.0,NaN,3.0,NaN,1.0,1.0,3.0,1,...,Secondhand,NaN,7.0,$3.90,skirt,calf-length maxi,11/11/2020,12/9/2018,NaN,Bottoms
1,1,Black Midi CL Circle Skirt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Gift,NaN,NaN,$0.00,skirt,calf-length maxi,11/11/2020,12/9/2018,NaN,Bottoms
2,2,Grey FL Maxi Skirt,NaN,1.0,1.0,NaN,NaN,NaN,NaN,2,...,NaN,NaN,NaN,$2.00,skirt,full-length maxi,11/11/2020,12/9/2018,NaN,Bottoms
3,3,Pink and Tan Pattern Maxi Skirt,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,Gift,NaN,NaN,$0.00,skirt,full-length maxi,11/11/2020,12/9/2018,NaN,Bottoms
4,4,Light Black Skinny Leg Jeans,NaN,1.0,NaN,NaN,NaN,3.0,7.0,2,...,New,NaN,NaN,$3.11,jeans,skinny leg,11/11/2020,12/9/2018,NaN,Bottoms

In [5]:
# Pull date from CSV
dresses_df = pd.read_csv('dresses.csv')

# View dataframe
dresses_df.head()

,Unnamed: 0,Wardrobe Tracking - Start Date 12/9/2018,Wears (11/2020),Wears (10/2020),Wears (9/2020),Wears (8/2020),Wears (7/2020),Wears (6/2020),Wears (5/2020),Wears (4/2020),...,Notes,Repairs/Tailoring,CPW,Unnamed: 35,Category,Subcategory - Length,Subcategory - Sleeves,Today,Date Started,Type
0,0,Blue and Yellow Jumpsuit,NaN,1.0,1.0,3.0,NaN,1.0,NaN,NaN,...,NaN,NaN,$15.83,NaN,jumpsuit,full length,sleeveless,11/11/2020,12/9/2018,Dresses
1,1,White Slip SL KL Dress,NaN,NaN,1.0,1.0,NaN,1.0,1.0,1,...,NaN,NaN,$4.89,NaN,dress,knee length,sleeveless,11/11/2020,12/9/2018,Dresses
2,2,Blue and White Polka Dot SL KL Dress,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1,...,NaN,NaN,$0.00,FL = Full Length,dress,knee length,sleeveless,11/11/2020,12/9/2018,Dresses
3,3,"Multicolor (orange, white, blue) SL KL Dress",NaN,NaN,NaN,1.0,NaN,NaN,NaN,1,...,NaN,NaN,$6.25,NaN,dress,knee length,sleeveless,11/11/2020,12/9/2018,Dresses
4,4,Black High-low SL KL Dress,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1,...,NaN,NaN,$0.00,NaN,dress,knee length,sleeveless,11/11/2020,12/9/2018,Dresses

In [6]:
# Pull data from CSV
shoes_df = pd.read_csv('shoes.csv')

# View datafram
shoes_df.head()

,Unnamed: 0,Wardrobe Tracking - Start Date 12/9/2018,Wears (11/2020),Wears (10/2020),Wears (9/2020),Wears (8/2020),Wears (7/2020),Wears (6/2020),Wears (5/2020),Wears (4/2020),...,Source,Notes,Repairs/Tailoring,CPW,Category,Today,Date Started,Subcategory - Sleeves,Subcategory - Length,Type
0,0,Black Leather Open-Toed Sandals,NaN,1.0,NaN,2.0,7.0,1.0,NaN,NaN,...,NaN,NaN,NaN,$1.38,sandals,11/11/2020,12/9/2018,NaN,NaN,Shoes
1,1,Brown Leather Trevi Flats,NaN,NaN,1.0,3.0,1.0,1.0,5.0,NaN,...,Slow Fashion,NaN,NaN,$7.71,flats,11/11/2020,12/9/2018,NaN,NaN,Shoes
2,2,Black Leather Iris Loafers,NaN,NaN,1.0,3.0,2.0,2.0,2.0,6.0,...,Slow Fashion,NaN,NaN,$4.27,flats,11/11/2020,12/9/2018,NaN,NaN,Shoes
3,3,Blue Leather Sneakers,1.0,2.0,3.0,4.0,1.0,3.0,NaN,1.0,...,Slow Fashion,NaN,NaN,$1.94,sneakers,11/11/2020,12/9/2018,NaN,NaN,Shoes
4,4,White Tennis Sneakers,1.0,1.0,1.0,3.0,5.0,1.0,12.0,3.0,...,Slow Fashion,NaN,NaN,$3.16,sneakers,11/11/2020,12/9/2018,NaN,NaN,Shoes

## Combine sheets into one DataFrame

In [7]:
# Combine dataframes to create master dataframe 
wardrobe_df = pd.concat([tops_df, bottoms_df, outerwear_df, shoes_df], ignore_index=True)

# Rename first column
wardrobe_df = wardrobe_df.rename(columns={'Wardrobe Tracking - Start Date 12/9/2018': 'Item', 'Acquired': 'Date Acquired'})

# Drop empty rows
wardrobe_df = wardrobe_df[wardrobe_df['Item'] != '']
    
# Replace STORAGE notes with NaN 
wardrobe_df = wardrobe_df.replace('STORAGE', np.nan)
wardrobe_df = wardrobe_df.replace('STORAGE ', np.nan)

# Clarify source of items that are not noted
wardrobe_df['Source'] = wardrobe_df['Source'].replace(np.nan, 'Fast Fashion')

# Remove unnecessary columns 
# Note: I removed November wears since that month is not complete
init_col_names = ['Wears/Month', 'CPW', 'Today', 'Start Date', 'Date Started', 'Wears (2018)', 'Wears (11/2020)', 'Total Wears']
for col_name in init_col_names:
    try:
        del wardrobe_df[col_name]
    except:
        pass
    
wardrobe_df.head()

,Unnamed: 0,Item,Wears (10/2020),Wears (9/2020),Wears (8/2020),Wears (7/2020),Wears (6/2020),Wears (5/2020),Wears (4/2020),Wears (3/2020),...,Cost,Brand,Source,Notes,Repairs/Tailoring,Category,Subcategory - Sleeves,Color,Subcategory - Length,Type
0,0,Brian's White Buttonup LS Shirt,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,...,0,Brian,Secondhand,NaN,NaN,shirt,long sleeve,cream/white/tan,NaN,Tops
1,1,Cream Turtleneck LS Shirt,1.0,1.0,NaN,NaN,NaN,1.0,1,NaN,...,4,Goodwill,Secondhand,NaN,NaN,shirt,long sleeve,cream/white/tan,NaN,Tops
2,2,Tie Dye Mineo LS Shirt,1.0,NaN,NaN,NaN,NaN,NaN,2,NaN,...,35,Andy Mineo,Fast Fashion,Winter Jam,NaN,shirt,long sleeve,multi,NaN,Tops
3,3,Forest Green Silk LS Shirt,2.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,23,Vince/Poshmark,Secondhand,NaN,NaN,shirt,long sleeve,green,NaN,Tops
4,4,Grey Heather LS Shirt,1.0,NaN,1.0,1,NaN,2.0,1,1,...,15,Old Navy,Fast Fashion,NaN,NaN,shirt,long sleeve,grey,NaN,Tops

In [8]:
# Pull list of column names and check for correct concatenation
column_names = list(wardrobe_df.columns)
print(column_names)

['Unnamed: 0', 'Item', 'Wears (10/2020)', 'Wears (9/2020)', 'Wears (8/2020)', 'Wears (7/2020)', 'Wears (6/2020)', 'Wears (5/2020)', 'Wears (4/2020)', 'Wears (3/2020)', 'Wears (2/2020)', 'Wears (1/2020)', 'Wears (12/2019)', 'Wears (11/2019)', 'Wears (10/2019)', 'Wears (9/2019)', 'Wears (8/2019)', 'Wears (7/2019)', 'Wears (6/2019)', 'Wears (5/2019)', 'Wears (4/2019)', 'Wears (3/2019)', 'Wears (2/2019)', 'Wears (1/2019)', 'Date Acquired', 'Cost', 'Brand', 'Source', 'Notes', 'Repairs/Tailoring', 'Category', 'Subcategory - Sleeves', 'Color', 'Subcategory - Length', 'Type']

In [9]:
# Store in CSV
wardrobe_df.to_csv('wardrobedatainitial.csv', index=False)

## Analyze data for total wears, cost per wear and wears per month

In [10]:
# Read in CSV
wardrobe_df = pd.read_csv('wardrobedatainitial.csv')
wardrobe_df.head()

,Unnamed: 0,Item,Wears (10/2020),Wears (9/2020),Wears (8/2020),Wears (7/2020),Wears (6/2020),Wears (5/2020),Wears (4/2020),Wears (3/2020),...,Cost,Brand,Source,Notes,Repairs/Tailoring,Category,Subcategory - Sleeves,Color,Subcategory - Length,Type
0,0,Brian's White Buttonup LS Shirt,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,...,0,Brian,Secondhand,NaN,NaN,shirt,long sleeve,cream/white/tan,NaN,Tops
1,1,Cream Turtleneck LS Shirt,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN,...,4,Goodwill,Secondhand,NaN,NaN,shirt,long sleeve,cream/white/tan,NaN,Tops
2,2,Tie Dye Mineo LS Shirt,1.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,...,35,Andy Mineo,Fast Fashion,Winter Jam,NaN,shirt,long sleeve,multi,NaN,Tops
3,3,Forest Green Silk LS Shirt,2.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,23,Vince/Poshmark,Secondhand,NaN,NaN,shirt,long sleeve,green,NaN,Tops
4,4,Grey Heather LS Shirt,1.0,NaN,1.0,1.0,NaN,2.0,1.0,1.0,...,15,Old Navy,Fast Fashion,NaN,NaN,shirt,long sleeve,grey,NaN,Tops

In [11]:
# Remove trailing whitespaces
columns = wardrobe_df.columns
for col in wardrobe_df.columns:
    if wardrobe_df[col].dtype == 'object':
        wardrobe_df[col] = wardrobe_df[col].str.rstrip()
    if wardrobe_df[col].dtype == 'int64' or wardrobe_df[col].dtype == 'float64':
        wardrobe_df[col] = wardrobe_df[col].replace(np.nan, 0)
        
wardrobe_df.head()

,Unnamed: 0,Item,Wears (10/2020),Wears (9/2020),Wears (8/2020),Wears (7/2020),Wears (6/2020),Wears (5/2020),Wears (4/2020),Wears (3/2020),...,Cost,Brand,Source,Notes,Repairs/Tailoring,Category,Subcategory - Sleeves,Color,Subcategory - Length,Type
0,0,Brian's White Buttonup LS Shirt,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0,Brian,Secondhand,NaN,0.0,shirt,long sleeve,cream/white/tan,NaN,Tops
1,1,Cream Turtleneck LS Shirt,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,4,Goodwill,Secondhand,NaN,0.0,shirt,long sleeve,cream/white/tan,NaN,Tops
2,2,Tie Dye Mineo LS Shirt,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,35,Andy Mineo,Fast Fashion,Winter Jam,0.0,shirt,long sleeve,multi,NaN,Tops
3,3,Forest Green Silk LS Shirt,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,23,Vince/Poshmark,Secondhand,NaN,0.0,shirt,long sleeve,green,NaN,Tops
4,4,Grey Heather LS Shirt,1.0,0.0,1.0,1.0,0.0,2.0,1.0,1.0,...,15,Old Navy,Fast Fashion,NaN,0.0,shirt,long sleeve,grey,NaN,Tops

In [12]:
# Determine columns that include wear counts
wear_cols = []

for col_name in column_names:
    if 'Wears' in col_name:
        wear_cols.append(col_name)
print(wear_cols)

['Wears (10/2020)', 'Wears (9/2020)', 'Wears (8/2020)', 'Wears (7/2020)', 'Wears (6/2020)', 'Wears (5/2020)', 'Wears (4/2020)', 'Wears (3/2020)', 'Wears (2/2020)', 'Wears (1/2020)', 'Wears (12/2019)', 'Wears (11/2019)', 'Wears (10/2019)', 'Wears (9/2019)', 'Wears (8/2019)', 'Wears (7/2019)', 'Wears (6/2019)', 'Wears (5/2019)', 'Wears (4/2019)', 'Wears (3/2019)', 'Wears (2/2019)', 'Wears (1/2019)']

In [13]:
# Calculate total wears
wardrobe_df['Total Wears'] = wardrobe_df[wear_cols].sum(axis=1)

wardrobe_df.head()

,Unnamed: 0,Item,Wears (10/2020),Wears (9/2020),Wears (8/2020),Wears (7/2020),Wears (6/2020),Wears (5/2020),Wears (4/2020),Wears (3/2020),...,Brand,Source,Notes,Repairs/Tailoring,Category,Subcategory - Sleeves,Color,Subcategory - Length,Type,Total Wears
0,0,Brian's White Buttonup LS Shirt,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,...,Brian,Secondhand,NaN,0.0,shirt,long sleeve,cream/white/tan,NaN,Tops,5.0
1,1,Cream Turtleneck LS Shirt,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,Goodwill,Secondhand,NaN,0.0,shirt,long sleeve,cream/white/tan,NaN,Tops,12.0
2,2,Tie Dye Mineo LS Shirt,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,Andy Mineo,Fast Fashion,Winter Jam,0.0,shirt,long sleeve,multi,NaN,Tops,5.0
3,3,Forest Green Silk LS Shirt,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,Vince/Poshmark,Secondhand,NaN,0.0,shirt,long sleeve,green,NaN,Tops,10.0
4,4,Grey Heather LS Shirt,1.0,0.0,1.0,1.0,0.0,2.0,1.0,1.0,...,Old Navy,Fast Fashion,NaN,0.0,shirt,long sleeve,grey,NaN,Tops,23.0

In [14]:
# Calculate cost per wear
wardrobe_df['Repairs/Tailoring'] = wardrobe_df['Repairs/Tailoring'].replace(np.nan, 0)
wardrobe_df['Cost per Wear'] = 0
for index, row in wardrobe_df.iterrows():
    if row['Total Wears'] > 0:
        wardrobe_df.loc[index, 'Cost per Wear'] = (row['Cost'] + row['Repairs/Tailoring'])/row['Total Wears']

wardrobe_df.head()

,Unnamed: 0,Item,Wears (10/2020),Wears (9/2020),Wears (8/2020),Wears (7/2020),Wears (6/2020),Wears (5/2020),Wears (4/2020),Wears (3/2020),...,Source,Notes,Repairs/Tailoring,Category,Subcategory - Sleeves,Color,Subcategory - Length,Type,Total Wears,Cost per Wear
0,0,Brian's White Buttonup LS Shirt,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,...,Secondhand,NaN,0.0,shirt,long sleeve,cream/white/tan,NaN,Tops,5.0,0.000000
1,1,Cream Turtleneck LS Shirt,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,Secondhand,NaN,0.0,shirt,long sleeve,cream/white/tan,NaN,Tops,12.0,0.333333
2,2,Tie Dye Mineo LS Shirt,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,Fast Fashion,Winter Jam,0.0,shirt,long sleeve,multi,NaN,Tops,5.0,7.000000
3,3,Forest Green Silk LS Shirt,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,Secondhand,NaN,0.0,shirt,long sleeve,green,NaN,Tops,10.0,2.300000
4,4,Grey Heather LS Shirt,1.0,0.0,1.0,1.0,0.0,2.0,1.0,1.0,...,Fast Fashion,NaN,0.0,shirt,long sleeve,grey,NaN,Tops,23.0,0.652174

In [15]:
# Calculate wears per month
wardrobe_df['Date Acquired'] = pd.to_datetime(wardrobe_df['Date Acquired'])
wardrobe_df['Wears per Month'] = ''
for index, row in wardrobe_df.iterrows():
    if row['Date Acquired'] > dt.datetime(2019, 1, 1):
        delta = dt.datetime(2020, 10, 31) - row['Date Acquired']
    else: 
        delta = dt.datetime(2020, 10, 31) - dt.datetime(2019, 1, 1)
    months = delta.days/30
    wardrobe_df.loc[index, 'Wears per Month'] = row['Total Wears']/months

wardrobe_df.head()

,Unnamed: 0,Item,Wears (10/2020),Wears (9/2020),Wears (8/2020),Wears (7/2020),Wears (6/2020),Wears (5/2020),Wears (4/2020),Wears (3/2020),...,Notes,Repairs/Tailoring,Category,Subcategory - Sleeves,Color,Subcategory - Length,Type,Total Wears,Cost per Wear,Wears per Month
0,0,Brian's White Buttonup LS Shirt,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,...,NaN,0.0,shirt,long sleeve,cream/white/tan,NaN,Tops,5.0,0.000000,1.80723
1,1,Cream Turtleneck LS Shirt,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,NaN,0.0,shirt,long sleeve,cream/white/tan,NaN,Tops,12.0,0.333333,0.538117
2,2,Tie Dye Mineo LS Shirt,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,Winter Jam,0.0,shirt,long sleeve,multi,NaN,Tops,5.0,7.000000,0.579151
3,3,Forest Green Silk LS Shirt,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,NaN,0.0,shirt,long sleeve,green,NaN,Tops,10.0,2.300000,0.791557
4,4,Grey Heather LS Shirt,1.0,0.0,1.0,1.0,0.0,2.0,1.0,1.0,...,NaN,0.0,shirt,long sleeve,grey,NaN,Tops,23.0,0.652174,1.03139

In [16]:
# Print list of column names
column_names_final = list(wardrobe_df.columns)
print(column_names_final)

['Unnamed: 0', 'Item', 'Wears (10/2020)', 'Wears (9/2020)', 'Wears (8/2020)', 'Wears (7/2020)', 'Wears (6/2020)', 'Wears (5/2020)', 'Wears (4/2020)', 'Wears (3/2020)', 'Wears (2/2020)', 'Wears (1/2020)', 'Wears (12/2019)', 'Wears (11/2019)', 'Wears (10/2019)', 'Wears (9/2019)', 'Wears (8/2019)', 'Wears (7/2019)', 'Wears (6/2019)', 'Wears (5/2019)', 'Wears (4/2019)', 'Wears (3/2019)', 'Wears (2/2019)', 'Wears (1/2019)', 'Date Acquired', 'Cost', 'Brand', 'Source', 'Notes', 'Repairs/Tailoring', 'Category', 'Subcategory - Sleeves', 'Color', 'Subcategory - Length', 'Type', 'Total Wears', 'Cost per Wear', 'Wears per Month']

In [17]:
# Rearrange columns
wardrobe_df = wardrobe_df[['Item', 
                           'Total Wears', 
                           'Cost per Wear', 
                           'Wears per Month', 
                           'Date Acquired', 
                           'Cost', 
                           'Source', 
                           'Repairs/Tailoring', 
                           'Color', 
                           'Type', 
                           'Category', 
                           'Subcategory - Sleeves', 
                           'Subcategory - Length',
                           'Wears (10/2020)', 
                           'Wears (9/2020)', 
                           'Wears (8/2020)', 
                           'Wears (7/2020)', 
                           'Wears (6/2020)', 
                           'Wears (5/2020)', 
                           'Wears (4/2020)', 
                           'Wears (3/2020)', 
                           'Wears (2/2020)', 
                           'Wears (1/2020)', 
                           'Wears (12/2019)', 
                           'Wears (11/2019)', 
                           'Wears (10/2019)', 
                           'Wears (9/2019)', 
                           'Wears (8/2019)', 
                           'Wears (7/2019)', 
                           'Wears (6/2019)', 
                           'Wears (5/2019)', 
                           'Wears (4/2019)', 
                           'Wears (3/2019)', 
                           'Wears (2/2019)', 
                           'Wears (1/2019)']]

wardrobe_df.head()

,Item,Total Wears,Cost per Wear,Wears per Month,Date Acquired,Cost,Source,Repairs/Tailoring,Color,Type,...,Wears (10/2019),Wears (9/2019),Wears (8/2019),Wears (7/2019),Wears (6/2019),Wears (5/2019),Wears (4/2019),Wears (3/2019),Wears (2/2019),Wears (1/2019)
0,Brian's White Buttonup LS Shirt,5.0,0.000000,1.80723,2020-08-09,0,Secondhand,0.0,cream/white/tan,Tops,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Cream Turtleneck LS Shirt,12.0,0.333333,0.538117,2018-12-19,4,Secondhand,0.0,cream/white/tan,Tops,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
2,Tie Dye Mineo LS Shirt,5.0,7.000000,0.579151,2020-02-15,35,Fast Fashion,0.0,multi,Tops,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Forest Green Silk LS Shirt,10.0,2.300000,0.791557,2019-10-18,23,Secondhand,0.0,green,Tops,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Grey Heather LS Shirt,23.0,0.652174,1.03139,2018-01-01,15,Fast Fashion,0.0,grey,Tops,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,2.0,3.0

In [18]:
# Export to CSV
wardrobe_df.to_csv('wardrobedata.csv', index=False)

In [22]:
# FExport to HTML
wardrobe_df.to_html('wardrobedata.html', index=False)